[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gamba_pick"
version = "0.9.0"
description = "Auto Gamba for Fun and Profit"
readme = { file = "README.md", content-type = "text/markdown" }
license = "GPL-3.0-or-later"
authors = [{ name = "Cycle Five", email = "cycle.five@proton.me" }]
maintainers = [{ name = "Cycle Five", email = "cycle.five@proton.me" }]
keywords = [
    "gambling",
    "casino",
    "automation",
    "browser-automation",
    "gamba",
    "betting",
    "playwright",
    "browser",
]
requires-python = ">=3.11"
classifiers = [
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    # "Development Status :: 5 - Production/Stable",
    # "Development Status :: 6 - Mature",
    # "Development Status :: 7 - Inactive",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Natural Language :: English",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Browsers",
    "Topic :: Games/Entertainment",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: Implementation :: CPython",
    "Typing :: Typed",
]
dependencies = [
    "pyotp>=2.9.0",
    "click>=8.2.1",
    "curl_cffi>=0.13.0",
    "playwright>=1.56.0",
    "patchright>=1.56.0",
    "camoufox>=0.4.11",
    "geoip2>=4.8.1",
    "msgspec>=0.19.0",
    "scrapling @ file:///home/lothrop/src/Scrapling",
]

[project.optional-dependencies]
shell = [
    "IPython>=8.3.0",     # The last version that supports Python 3.10
    "markdownify>=1.2.0",
]

[project.urls]
Homepage = "https://github.com/Martingale-Distributed/gamba_pick"
Documentation = "https://gamba-pick.readthedocs.io/en/latest/"
Repository = "https://github.com/Martingale-Distributed/gamba_pick"
"Bug Tracker" = "https://github.com/Martingale-Distributed/gamba_pick/issues"

[project.scripts]
gamba-pick = "gamba_pick.cli:main"

[tool.setuptools]
zip-safe = true
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["gamba_pick*"]
